// Generated by CoffeeScript 1.2.1-pre
var graph, loadingMessageView, throbberView;

window.appModel = new Backbone.Model;

throbberView = new hv.LoadingView({
  el: "#throbber",
  model: appModel
});

loadingMessageView = new hv.LoadingView({
  el: "#loadingMessage",
  model: appModel
});

graph = new hv.Graph({
  el: "#graph",
  model: appModel
});

appModel.set({
  loading: true,
  loadingText: 'Fetching History...'
});

console.time("Getting historyItems");

console.profile("Getting historyItems");

chrome.history.search({
  text: "",
  startTime: 0,
  maxResults: 0
}, function(historyItems) {
  var allVisits, c;
  allVisits = [];
  c = historyItems.length;
  return historyItems.forEach(function(historyItem) {
    return chrome.history.getVisits({
      url: historyItem.url
    }, function(visits) {
      var visit, _i, _len;
      for (_i = 0, _len = visits.length; _i < _len; _i++) {
        visit = visits[_i];
        visit.historyItem = historyItem;
        visit.date = new Date(visit.visitTime);
        visit.day = new Date(visit.visitTime);
        visit.day.setHours(12);
        visit.day.setMinutes(0);
        visit.day.setSeconds(0);
        visit.day.setMilliseconds(0);
        allVisits.push(visit);
      }
      c--;
      if (c === 0) {
        console.timeEnd("Getting historyItems");
        console.profileEnd("Getting historyItems");
        return appModel.set({
          allVisits: allVisits
        });
      }
    });
  });
});
